import random
import string

from django.db import models


class TinyUrl(models.Model):
    full_url = models.URLField(unique=True)
    short_url = models.CharField(unique=True, max_length=7)  # generated by create_short_url function
    hit_count = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.short_url:
            self.short_url = self.create_short_url()
        super().save(*args, **kwargs)

    @staticmethod
    def create_short_url():
        short_url = ''.join(random.choices(string.ascii_letters + string.digits, k=7))
        while TinyUrl.objects.filter(short_url=short_url).exists():
            short_url = ''.join(random.choices(string.ascii_letters + string.digits, k=7))
        return short_url
