# Generated by Django 5.0.6 on 2024-05-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True)),
                ('short_url', models.CharField(max_length=7, unique=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
